### ISSUE TITLE
File proxy sometimes writes partial file

### ISSUE THREAD

**Issue by fonsp** [JuliaComputing/pluto-vscode#22]
<img width="519" alt="Schermafbeelding 2021-11-24 om 15 54 42" src="https://user-images.githubusercontent.com/6933510/143261278-7908cdcd-0eeb-4611-ae17-2a3790c69ad7.png">

This happened on https://github.com/fonsp/Pluto.jl/blob/main/src/webserver/Firebasey.jl

**Comment by fonsp** [comment]
The file proxy stopped working afterwards, I did not have access to the logs

**Comment by ChiCubed** [comment]
Could you make a release with this fix in it? I ran into this using the latest version on the VSCode marketplace and I think prior to the fix the file is getting truncated to ~6k all the time. That's pretty bad, since even just importing a package with too many dependencies can kill the notebook through the manifest string.
